# Generated by Django 5.0.4 on 2024-04-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_tipo_equipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_equipos',
            name='estado_respaldo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipo_equipos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
