# Generated by Django 5.0.4 on 2024-04-18 17:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_tipo_equipos_estado_respaldo_alter_tipo_equipos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes_Mantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('trabajo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(3)])),
                ('estado', models.CharField(max_length=40)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.clientes')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.tipo_equipos')),
            ],
            options={
                'db_table': 'ordenes_mantenimiento',
            },
        ),
    ]
