# Generated by Django 5.0.4 on 2024-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_ordenes_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'accesorios',
            },
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='contrasena',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='desea_respaldo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='detalles_dano',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='estado_equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='accesorios',
            field=models.ManyToManyField(blank=True, to='panel.accesorio'),
        ),
    ]
