# Generated by Django 5.0.4 on 2024-09-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes_mantenimiento',
            name='estado',
        ),
        migrations.AddField(
            model_name='ordenes_mantenimiento',
            name='estado',
            field=models.ManyToManyField(blank=True, to='panel.estado'),
        ),
    ]
